### ISSUE TITLE
ngram case-sensitive output

### ISSUE THREAD

**Issue by David134679** [seancarmody/ngramr#29]
Hello,

Great package and has been very helpful already!  One minor bug, when using ngram(..., case_ins = TRUE) the correct data is extracted however the automatic output still states "Case-sensitive: TRUE".

This may be intentional since the freq are indeed case sensitive since it just extracts both the freq for lowercase and the freq for uppercase.  I just thought I'd mention it because I'm not sure what this part of the output would be used for otherwise.  Thanks for your contribution to the R community!

Blessings,
David

**Comment by seancarmody** [comment]
Thanks David - that is a bug (one I'd fixed in the development version but neglected to get to the production version). It is fixed now with the latest patch (5994f5b9a6c22cd68b44b47b037e187e7e5a0358).
