### ISSUE TITLE
problem with stringr

### ISSUE THREAD

**Issue by danhart228** [seancarmody/ngramr#35]
When I run these commands:

library (ngramr)
 ng  <- ngram(c("hacker", "programmer"), year_start = 1950)

I get this message:  

Error in stringr::str_split(grep("drawD3Chart", json, value = TRUE), ",")[[1]] : 
  subscript out of bounds
In addition: Warning message:
In ngram_fetch_data(html) : NAs introduced by coercion

**Comment by seancarmody** [comment]
Let me have a look - it's possible that Google has changed the format of it's website

**Comment by seancarmody** [comment]
Yes - the website format has changed. I'll need to update the code and release an update. I will keep you posted!

**Comment by danhart228** [comment]
Thank you!  I appreciate your attentiveness to the issue, and love the package!

Daniel Hart
Prevention Science and Psychology
Rutgers University-Camden
________________________________

**Comment by seancarmody** [comment]
Thanks. Making progress - should be ready to upload a new version within a day

**Comment by danhart228** [comment]
Excellent news to learn about the progress on the ngramr package.  Many thanks!

Daniel Hart
Prevention Science and Psychology
Rutgers University-Camden
________________________________

**Comment by seancarmody** [comment]
I have addressed all of the problems and the version here on GitHub should now work. I am now going through the release testing routine. I will let you know when it's up on CRAN as well.

**Comment by danhart228** [comment]
Very much appreciated!  Thank you!

Daniel Hart
Prevention Science and Psychology
Rutgers University-Camden
________________________________

**Comment by seancarmody** [comment]
CRAN release up, so I will close this issue. Let me know if you have any more problems.

**Comment by danhart228** [comment]
Very, very much appreciated!

Daniel Hart
Prevention Science and Psychology
Rutgers University-Camden
________________________________
