### ISSUE TITLE
Not getting an answer from google

### ISSUE THREAD

**Issue by pooryaselkghafari** [seancarmody/ngramr#36]
I get this error while running my code:

Warning: NAs introduced by coercionError in stringr::str_split(grep("drawD3Chart", json, value = TRUE), ",")[[1]] : 
  subscript out of bounds

All my phrases have plots in n-gram. My code was working a week ago now it just sends me errors.

**Comment by seancarmody** [comment]
Have you updated to version 1.7.7? There was a change google made which broke the earlier versions. 1.7.7 should not give the error you saw.

**Comment by seancarmody** [comment]
Note that the names of the corpuses have changed so if you are specifying a corpus you will need to update your code slightly

**Comment by seancarmody** [comment]
I am going to assume the more recent releases have solved this issue unless I hear otherwise and will shortly close the issue

**Comment by pooryaselkghafari** [comment]
Hello,

Thank you for the response. Yes, the issue is resolved. Sorry for the late feedback.

**Comment by seancarmody** [comment]
No problem. I'm glad it's all working for you now.
