### ISSUE TITLE
Apparent new problem.

### ISSUE THREAD

**Issue by danhart228** [seancarmody/ngramr#40]
Hi,

  Perhaps google has changed its site again?  

 ng  <- ngram(c("hacker", "programmer"), year_start = 1950)
Please check Google's Ngram Viewer site is up.
Timeout was reached: [books.google.com] Send failure: Connection was aborted

> ng  <- ngram(c("hacker", "programmer"), year_start = 1950)
Error parsing ngram data, please contact package maintainer.
Here's the original error message:
subscript out of bounds
Error occurred in the following code:
[[stringr::str_split(grep("drawD3Chart", years, value = TRUE), ",")1

**Comment by seancarmody** [comment]
Looks like it! Getting onto it now...

**Comment by seancarmody** [comment]
Yes, Google updated their site (again) which broke my code. I have made some modifications which should make it work now. I will complete testing and republish to CRAN. In the meantime you can try out the development version. This requires use of the dev tools package, so install that if you haven't already and then try:
```
library(devtools)
install_github("seancarmody/ngramr", "develop")
library(ngramr)
```
Let me know if that works.

**Comment by danhart228** [comment]
Outstanding!  Working perfectly, as far as I can tell.  Many, many thanks!

Daniel Hart
Prevention Science and Psychology
Rutgers University-Camden
________________________________

**Comment by seancarmody** [comment]
Thanks. Updated version now published on CRAN.
