### ISSUE TITLE
NGRAM fails to install osx 12.6  

### ISSUE THREAD

**Issue by news1537** [seancarmody/ngramr#41]
I have tried (install_packages)(Install_local)
All return  as this is not a mac binary package
Error in install.packages : file ‘/var/folders/dq/kg1jg0jj7pldyf4k_30pqgg80000gn/T//Rtmp3rwJw3/downloaded_packages/cli_3.4.1.tgz’ is not a macOS binary package

I am using R 4.1

**Comment by seancarmody** [comment]
That looks like a problem with installing the package `cli` (which `ngramr` depends on). What happens if you run
```
install.packages("cli", verbose = TRUE)
```

**Comment by seancarmody** [comment]
Any luck getting the package installed?

**Comment by seancarmody** [comment]
I will close this issue in a couple of days if there are no further comments
