### ISSUE TITLE
ngramr not working

### ISSUE THREAD

**Issue by danhart228** [seancarmody/ngramr#43]
Hi, your great package seems to be not working.  Many thanks for your maintaining this package.

 ng  <- ngram(c("hacker", "programmer"), year_start = 1950)
Error parsing ngram data, please contact package maintainer.
Here's the original error message:
subscript out of bounds
Error occurred in the following code:
[[stringr::str_split(grep("drawD3Chart", years, value = TRUE), ",")1

**Comment by seancarmody** [comment]
Hi Dan. Do you have the latest version? It broke again a couple of days ago and 1.9.1 fixed the problem but Google may have made more changes since

**Comment by danhart228** [comment]
Perfect!  Seems to be running now.  My apologies for not checking that.  I really appreciate your maintenance of this package!

Daniel Hart
Prevention Science and Psychology
Rutgers University-Camden
________________________________

**Comment by seancarmody** [comment]
Glad to hear it!
